### ISSUE TITLE
minimap not working on MacOS 10.12.1 and Atom 1.12.3

### ISSUE THREAD

**Issue by Raydem0n** [atom-minimap/minimap#539] opened 2016-11-16 10:03 UTC
minimap not working on MacOS 10.12.1 and Atom 1.12.3

**Comment by Raydem0n** [comment] 2016-11-16 10:11
maybe conflict with ActivePower plugin. Disable active-power and re-install minimap fix the issue.

**Comment by abe33** [comment] 2016-11-29 08:18
Looks like a duplicate of #541 for me, could you confirm that downgrading to v4.25.* fix that issue?

**Comment by abe33** [comment] 2017-01-11 10:00
Hey all, 1.13 was finally released! Which means that you all will be able to use the v4.26.x versions.

**Closed** 2020-11-21 06:23 UTC
