### ISSUE TITLE
Minimap smudges out on high DPI windows after repeated scrolling

### ISSUE THREAD

**Issue by isparavanje** [atom-minimap/minimap#367] opened 2015-07-18 22:26 UTC
After scrolling up and down multiple times, the minimap looks like this:
<img width="556" alt="capture" src="https://cloud.githubusercontent.com/assets/10181358/8763747/41a83ef6-2d72-11e5-883c-f060c0f290e5.PNG">

I am using Atom 1.0.2 on Windows 10. It started happening with the latest minimap update, 4.12.0

**Comment by abe33** [comment] 2015-07-20 13:16
Hi there, it's really unlikey that the problem started with 4.12, the ony change is the support of touch events when dragging the minimap, nothing render related. 

But are you using a float value in your minimap config? It looks like float values gives this kind of blur, and with repetitive copy/pasting of the offscreen canvas the blur increases.

**Comment by isparavanje** [comment] 2015-07-20 14:11
I have not changed the configs, perhaps high dpi scaling caused some values to behave like floats? I've got no idea, I'm just guessing. 



On Mon, Jul 20, 2015 at 6:16 AM -0700, "Cédric Néhémie" <notifications@github.com> wrote:












Hi there, it's really unlikey that the problem started with 4.12, the ony change is the support of touch events when dragging the minimap, nothing render related. 



But are you using a float value in your minimap config? It looks like float values gives this kind of blur, and with repetitive copy/pasting of the offscreen canvas the blur increases.

**Comment by abe33** [comment] 2015-07-20 15:44
Can you record a gif of this effect? Also, can you tell hat is your configuration? (Atom version, Pigments version, configuration of pigments available in `config.json`)

**Comment by isparavanje** [comment] 2015-07-20 21:23
Atom Version: 1.0.2
Minimap Version: 4.12.0

![minimap_bug](https://cloud.githubusercontent.com/assets/10181358/8787755/7c4841e8-2efb-11e5-9e8d-92411cd54c94.gif)

Config snippet:
'''cson
  minimap:
    scrollAnimation: true
    absoluteMode: true
    useHardwareAcceleration: false
'''

**Comment by abe33** [comment] 2015-07-21 08:05
Ok, I think the issue comes from the 125% scaling, `window.devicePixelRatio` probably return `1.25` so it introduces floats where it shouldn't. I'll try to think of a way to fix that without having to use rounding but I fear this will be the only reasonable solution.

**Comment by alexrussell** [comment] 2015-08-28 10:18
This happens for me too - the problem is that it's not always blurry, just gets that way as you scroll (and progressively worse, especially if you scroll faster). If you start to edit a section, then sometimes it clears itself up either partially or completely. Similarly, if you switch tabs it clears itself up too.

In my case yes I'm using a float value (char height 1.7) so I'm very much doing it in, but yeah it's not something that's there at first so I don't think the floaty values *alone* are the cause.

Gif (sorry for filesize):

![minimap](https://cloud.githubusercontent.com/assets/412784/9544165/487eafac-4d76-11e5-8f2d-79418d2bd512.gif)

**Comment by seemethere** [comment] 2015-09-02 18:29
I'm getting this problem as well.

Here's a picture of my experience.

<img width="405" alt="minimap error" src="https://cloud.githubusercontent.com/assets/1700823/9640317/a3dcb9bc-5176-11e5-9992-80f4e56e90ab.PNG">

**Comment by abe33** [comment] 2015-09-08 12:52
Honestly, I'm not really sure how to fix that. 

The obvious solution would be to prevent floating values in settings and all canvas computation, but that won't fix things when it's the `devicePixelRatio` that contains a float, and sadly I don't have access to a device with this kind of pixel ratio. If someone is willing to experiment with rounding values in the canvas drawer to see how it behaves it could lead to a better solution.

**Comment by alexrussell** [comment] 2015-09-08 13:02
The thing that gets me is that the minimap is not *always* smudging - just after a bit of scrolling up and down.

I'm not sure what this actually means, though. To me, it means that the issue is not the actual drawing but more the clearing/repainting of the canvas. But then, without using floats, everything works fine so it definitely has something to do with the floats.

**Comment by jonas-schievink** [comment] 2015-09-08 13:24
I think I have a fix. In `lib/mixins/canvas-drawer.coffee` in function `copyBitmapPart` replace the first line:
```
lineHeight = @minimap.getLineHeight() * devicePixelRatio
```
with
```
lineHeight = Math.ceil(@minimap.getLineHeight() * devicePixelRatio)
```

(maybe `Math.round` would be better, I don't know. However `Math.floor` causes parts at the bottom of the minimap not to render)

**Comment by abe33** [comment] 2015-09-08 14:45
@alexrussell: As you guessed the issue doesn't come from the painting itself, but from the continuous copy between the onscreen and the offscreen canvas. Basically, when we need to repaint the minimap we first check which range is still valid, and copy that part from the offscreen canvas, and then we repaint the rest of the minimap. But when floats are involved, using `drawImage` will starts smoothing things, and repeating this operation will only increase the smudge effect. Sadly there's no control over this in the `drawImage` method so avoiding floats is the only realistic solution.

@jonas-schievink: I was thinking of something like this. If you can try that patch for some time to make sure there's no side effects I'll integrate that fix in the minimap. As for the Math.floor issue you had, I think it's because the first and last visible lines computed by the model didn't changed, so if you increase the rendered line height it won't be noticeable as you'll draw past the minimap bounds, but if it's smaller then the rendered minimap will be smaller than the available space. That make me think that there's probably some other places when a rounding will be needed, I'll check that when I get some spare time.

**Comment by jonas-schievink** [comment] 2015-09-08 14:57
I did notice something: Lines get brighter when editing them. Not sure if it's related, though. Looks as if the lines are just rendered on top of each other without clearing or filling the background. Since the text opacity is < 0, they look brighter.
<img width="116" alt="minimap" src="https://cloud.githubusercontent.com/assets/1786438/9737979/9b694dcc-5649-11e5-861d-e09494c44264.png">

**Comment by jonas-schievink** [comment] 2015-09-08 17:25
Regardless of where I inserted `Math.floor/ceil/round`, something always broke. I then found a much simpler fix that doesn't break anything: `s/devicePixelRatio/1/g`. I have no clue what a proper solution would look like, so I'll use this for now.

**Comment by fundon** [comment] 2015-12-22 01:43
Rounds the `devicePicelRatio` is landed in https://github.com/atom-minimap/minimap/blob/master/CHANGELOG.md#v4180-2015-12-11.

**Comment by alexrussell** [comment] 2015-12-22 14:15
A-ha yes, this is 100% fixed for me (including use of a non-integral line height in the settings).

**Comment by jonas-schievink** [comment] 2015-12-22 14:34
Indeed :tada:

**Comment by abe33** [comment] 2015-12-22 15:21
@alexrussell, @jonas-schievink  Glad to hear that it's finally fixed for you, do you think we can close this issue then?

**Comment by jonas-schievink** [comment] 2015-12-22 18:58
@abe33 I've played around with a few settings and couldn't reproduce this issue, so I think this can be closed (a regression test would be nice, but I guess that's not really feasable)

**Comment by fundon** [comment] 2015-12-23 06:53
Great.  Thank you for your feedback.

The test was landed in https://github.com/atom-minimap/minimap/blob/master/spec/minimap-spec.js#L594-L611.

Closed.

**Closed by fundon** 2015-12-23 06:53 UTC
Labels: bug, help-needed

**Comment by abe33** [comment] 2015-12-23 08:31
@jonas-schievink it should be feasable, I'll just the time to properly write them.
