### ISSUE TITLE
empty lines are not shown

### ISSUE THREAD

**Issue by petKitsune** [atom-minimap/minimap#768] opened 2021-01-18 09:35 UTC
love it that minimap is still maintained

but in the last update the empty lines are not shown anymore
perhaps a thing in coding but i use Atom for writing books in LaTeX
minimap shows only 1 long paragraph this way
is there or will there be an option to turn this on or of?

win10 x64 20H2
Atom 1.54
minimap 4.39.3

**Comment by aminya** [comment] 2021-01-18 09:40
This is caused by the latest release. I will revert it.

**Comment by aminya** [comment] 2021-01-18 09:43
Fixed in https://github.com/atom-minimap/minimap/commit/86767a08dde8d7eb2d6c3931862ea8f0c4a86900

**Closed by aminya** 2021-01-18 09:43 UTC
Labels: bug

**Comment by petKitsune** [comment] 2021-01-18 10:46
thanks 👍
