### ISSUE TITLE
Implement kite promotion?

### ISSUE THREAD

**Issue by MrStonedOne** [atom-minimap/minimap#616] opened 2017-07-24 20:48 UTC
re: #588 

Attempting to stop the discussion is a bad action.

You have now made it clear that a fork is necessary

**Comment by Arcanemagus** [comment] 2017-07-24 20:51
@MrStonedOne As stated, the purpose of #588 (discussion about the Kite "integration") has been resolved. The Kite integration was removed from this package, and a 3rd party has been added to "keep things honest".

Starting in on a discussion of the merits of forking within open source communities had no reason to be in that issue.

**Comment by MrStonedOne** [comment] 2017-07-24 20:53
I understand that, I just don't care.

It didn't NEED to be there, but thats where the discussion was happening, and attempting to abuse control over the issue tracker it happened in to stifle discussion is still a bad action

**Comment by diegoperini** [comment] 2017-07-25 00:11
I would understand if the owners want to prevent more issues to be opened about the same topic but closing a thread completely is plain censorship. I sincerely believe @mehcode wants the community to stay unified but no matter how honest he looks, the first thing a newly added contributor does shouldn't be that spooky. It now looks he is bought too.

I'm really sorry @mehcode , you probably doesn't deserve my last statement. I just have to stay skeptical in such environment. I'll prefer to use your fork instead of this main one. Can I kindly ask you to not delete the fork and/or not revoke it from apm even when you decide to leave it orphaned?

**Comment by mehcode** [comment] 2017-07-25 00:38
There is a reason why *I* locked the issue and not Kite. You can [look me up](https://www.linkedin.com/in/ryan-leckey-9aa63532/). I'm very transparent. I have no personal, professional, or financial interest in Kite. My only interest is in the propagation of Atom as the **best** editor experience. Nor do I have a personal, professional, or financial interest in GitHub. I simply want a professional, open editor that has a solid experience. 

If you still doubt me at this point, I really have no way to convince you besides inviting you to browse my [GitHub activity](https://github.com/mehcode).

---

> I would understand if the owners want to prevent more issues to be opened about the same topic but closing a hot thread completely is plain censorship.

> Attempting to stop the discussion is a bad action.

GitHub is not a public forum. It's a public issue tracker. Talking constructively about bugs, feature requests, etc. is totally fine. A little deviation is acceptable. But let's be honest, that thread was never going to end until it was locked.

I'm not going to lock this thread ( at this time ). I am going to close it. It's not a bug, feature request, or constructive discussion relating to the Minimap package as it stands, today. 

I've pledged to help Minimap, for Minimap (not Kite). It does no good to keep issues open merely to complain. There are many other ways to do this on the internet.

**Closed by mehcode** 2017-07-25 00:38 UTC

**Comment by MrStonedOne** [comment] 2017-07-25 04:25
>I've pledged to help Minimap, for Minimap (not Kite). It does no good to keep issues open merely to complain. There are many other ways to do this on the internet.

You don't have to keep the issue report open, close it, mute the thread, and just ignore it and let it be.

**Comment by diegoperini** [comment] 2017-07-25 07:58
@mehcode thanks for bothering, I really didn't mean to offend you and I apologize if it is heard otherwise. My criticism was honest and maybe brutal, but not angry or insulting. I believe (as I mentioned before) you are not corrupted or bought. The way things happened one after another wasn't apologetic enough from Kite's side and when you are added the project as a 3rd party contributor, it was a legitimate expectation to see you remain skeptical to Kite's true intentions. Maybe they really regret what happened and it really won't happen again. Out of good intentions, you cooperated almost like a saint (this is a compliment 👍). I as a random guy from the internet, without knowing who you really are, felt suspicious and hushing wouldn't resolve things on my side.

Whether put there accidental or not, the removed commit was a tool for IP theft. It is not something to be forgotten in a day. It deserves to be talked, reminded again and again. Bending the issue tracker's real purpose for the sake of scratching this to history, making sure it will be seen by future users is not breaking the rules but a **responsibility**.

A discussion doesn't have to end in a day, week or month. It will still be constructive if it is free of hate speech and bashing. When people get bored or trust is reconstructed, it will resolve by itself without further intervention. Keeping the issue closed while allowing more comments to be added is the right decision.

I apologize again for any inconvenience I caused and hope you to be a part of happy, fruitful collaboration.
