### ISSUE TITLE
lost minimap after updating to 1.44

### ISSUE THREAD

**Issue by vgkinis** [atom-minimap/minimap#692] opened 2020-02-11 14:28 UTC
I do not seem to be able to toggle on the minimap since I moved to 1.44
Anyone else has the same problem?

**Comment by hodossy** [comment] 2020-02-11 15:11
I have the same problem with 1.44.0. My minimap is at 4.29.9 with minimap-highlight-selected 4.6.1.

**Comment by Mullans** [comment] 2020-02-11 18:34
I'm getting the exact same error message from 394 in main.js, except I'm using atom 1.43. It's not liking the minimapElement.attach() for some reason.

**Comment by thatrandomfrenchdude** [comment] 2020-02-11 22:41
I received the same error - uninstalled an reinstalled atom to 1.44.
minimap 4.29.9

**Comment by maky-hnou** [comment] 2020-02-13 08:42
I had some issues with minimap. I am using it alongside with some other packages. After I updated some of the packages, I lost minimap display too.  
The problem was solved after I changed the line 391 from the function `initSubscriptions` in the file `minimap/lib/main.js`:  
from: `let minimapElement = atom.views.getView(minimap)`  
to: `let minimapElement = this.minimapViewProvider(minimap)`  
More details in [this link](https://github.com/spadarian/docblock-python/issues/43)

**Comment by alythobani** [comment] 2020-02-19 17:19
Same issue, I don't even need `docblock-python` anymore so I just disabled it and minimap is working again. Weird stuff but thanks for the fix 👍

**Comment by maky-hnou** [comment] 2020-02-20 16:49
@alythobani The problem is in minimap. After I made the changes I posted in the first comment, I have both minimap and docblock-python working.

**Comment by UziTech** [comment] 2020-11-21 06:41
duplicate of #693

**Closed by UziTech** 2020-11-21 06:41 UTC
