### ISSUE TITLE
Uncaught TypeError: atom.views.pollDocument is not a function

### ISSUE THREAD

**Issue by ghanim-ga1206290** [atom-minimap/minimap#703] opened 2020-05-28 15:49 UTC
Uncaught TypeError: atom.views.pollDocument is not a function

/Users/GhanimAL_Ghanim/.atom/packages/minimap/lib/minimap-element.js:345
Hide Stack Trace
TypeError: atom.views.pollDocument is not a function
    at HTMLElement.attachedCallback (/Users/GhanimAL_Ghanim/.atom/packages/minimap/lib/minimap-element.js:345:39)
    at HTMLElement.value [as attachedCallback] (/Users/GhanimAL_Ghanim/.atom/packages/minimap/node_modules/atom-utils/lib/register-or-update-element.js:15:57)
    at HTMLElement.activeItemChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:152:22)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1201250)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1202691)
    at Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:455971)
    at Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:458219)
    at Workspace.open (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:431887)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:717783
    at async Promise.all (index 0)
    at AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:718064)

**Comment by aminya** [comment] 2020-11-21 06:21
Duplicate of https://github.com/atom-minimap/minimap/issues/632

**Closed by aminya** 2020-11-21 06:21 UTC
