### ISSUE TITLE
error or startup

### ISSUE THREAD

**Issue by kusabnis** [atom-minimap/minimap#627] opened 2017-08-25 18:45 UTC
just downloaded the latest version of atom on windows and was greeted with an error message :

[Enter steps to reproduce:]

1. New System
2. download and setup atom

**Atom**: 1.19.3 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package 4.26.8

### Stack Trace

Uncaught TypeError: atom.views.pollDocument is not a function

```
At C:\Users\Kumar\.atom\packages\minimap\lib\minimap-element.js:345

TypeError: atom.views.pollDocument is not a function
    at HTMLElement.attachedCallback (/packages/minimap/lib/minimap-element.js:345:39)
    at /packages/minimap/node_modules/atom-utils/lib/register-or-update-element.js:15:57)
    at HTMLElement.module.exports.PaneContainerElement.rootChanged (~/AppData/Local/atom/app-1.19.3/resources/app/src/pane-container-element.js:42:14)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.19.3/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.19.3/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.setRoot (~/AppData/Local/atom/app-1.19.3/resources/app/src/pane-container.js:138:24)
    at PaneContainer.replaceChild (~/AppData/Local/atom/app-1.19.3/resources/app/src/pane-container.js:146:16)
    at PaneAxis.module.exports.PaneAxis.reparentLastChild (~/AppData/Local/atom/app-1.19.3/resources/app/src/pane-axis.js:232:25)
    at PaneAxis.module.exports.PaneAxis.removeChild (~/AppData/Local/atom/app-1.19.3/resources/app/src/pane-axis.js:197:27)
    at ~/AppData/Local/atom/app-1.19.3/resources/app/src/pane-axis.js:240:30
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.19.3/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.19.3/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Pane.module.exports.Pane.destroy (~/AppData/Local/atom/app-1.19.3/resources/app/src/pane.js:931:28)
    at Pane.module.exports.Pane.removeItem (~/AppData/Local/atom/app-1.19.3/resources/app/src/pane.js:650:27)
    at Pane.module.exports.Pane.destroyItem (~/AppData/Local/atom/app-1.19.3/resources/app/src/pane.js:706:22)
    at TabBarView.module.exports.TabBarView.closeTab (~/AppData/Local/atom/app-1.19.3/resources/app/node_modules/tabs/lib/tab-bar-view.js:341:32)
    at HTMLDivElement.TabView.didClickCloseIcon (~/AppData/Local/atom/app-1.19.3/resources/app/node_modules/tabs/lib/tab-bar-view.js:229:25)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.29.17 
minimap 4.26.8 
```

**Comment by dmitrif** [comment] 2017-08-28 14:43
Update minimap to `4.29.6`.

**Comment by aminya** [comment] 2020-11-21 06:22
Duplicate of https://github.com/atom-minimap/minimap/issues/632

**Closed** 2020-11-21 06:22 UTC
