### ISSUE TITLE
Failed to load the minimap package

### ISSUE THREAD

**Issue by shuucream** [atom-minimap/minimap#332] opened 2015-05-19 15:14 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.199.0
**System**: Unknown Windows Version
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.9.0

### Stack Trace

Failed to load the minimap package

```
At Cannot find module 'event-kit'

Error: Cannot find module 'event-kit'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (C:\Users\shuu\AppData\Local\atom\app-0.199.0\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\shuu\.atom\packages\minimap\lib\main.coffee:1:34)
  at Object.<anonymous> (C:\Users\shuu\.atom\packages\minimap\lib\main.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\shuu\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\shuu\AppData\Local\atom\app-0.199.0\resources\app.asar\src\package.js:707:34)
  at C:\Users\shuu\AppData\Local\atom\app-0.199.0\resources\app.asar\src\package.js:186:28
  at Package.module.exports.Package.measure (C:\Users\shuu\AppData\Local\atom\app-0.199.0\resources\app.asar\src\package.js:163:15)
  at Package.module.exports.Package.load (C:\Users\shuu\AppData\Local\atom\app-0.199.0\resources\app.asar\src\package.js:177:12)
  at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\shuu\AppData\Local\atom\app-0.199.0\resources\app.asar\src\package-manager.js:355:14)
  at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\shuu\AppData\Local\atom\app-0.199.0\resources\app.asar\src\package-manager.js:325:14)
  at Atom.module.exports.Atom.startEditorWindow (C:\Users\shuu\AppData\Local\atom\app-0.199.0\resources\app.asar\src\atom.js:633:21)
  at Object.<anonymous> (C:\Users\shuu\AppData\Local\atom\app-0.199.0\resources\app.asar\src\window-bootstrap.js:12:8)
  at Object.<anonymous> (C:\Users\shuu\AppData\Local\atom\app-0.199.0\resources\app.asar\src\window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\shuu\AppData\Local\atom\app-0.199.0\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at setupWindow (file:///C:/Users/shuu/AppData/Local/atom/app-0.199.0/resources/app.asar/static/index.js:91:23)
  at window.onload (file:///C:/Users/shuu/AppData/Local/atom/app-0.199.0/resources/app.asar/static/index.js:32:7)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "fileEncoding": "shiftjis"
  }
}
```

### Installed Packages

```coffee
# User
Atom-Localization, v1.16.1
minimap, v4.9.0

# Dev
No dev packages
```

**Comment by abe33** [comment] 2015-05-19 15:27
Hmm, can you check if the `event-kit` module is installed in the `node_modules` directory of the minimap package? It looks like an installation issue. Have you tried uninstalling/installing it again?

**Comment by Chris54721** [comment] 2015-05-23 16:18
Reinstalling solved the problem for me.

**Comment by rafaelstz** [comment] 2015-06-01 13:49
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.204.0
**System**: Mac OS X 10.10.3
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.9.1


### Stack Trace

Failed to load the minimap package

```
At /Users/rafaelcg/.atom/packages/minimap/lib/mixins/dom-styles-reader.coffee:91
      _ref3 = rotate‡(r, g, b, hue), r = _ref3[0], g = _ref3[1], b = _ref3[2];
                    ^
Unexpected token ILLEGAL

/Users/rafaelcg/.atom/packages/minimap/lib/mixins/dom-styles-reader.coffee:91
      _ref3 = rotate‡(r, g, b, hue), r = _ref3[0], g = _ref3[1], b = _ref3[2];
                    ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:435:25)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/rafaelcg/.atom/packages/minimap/lib/minimap-element.coffee:13:21)
    at Object.<anonymous> (/Users/rafaelcg/.atom/packages/minimap/lib/minimap-element.coffee:672:4)
    at Module._compile (module.js:452:26)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "magento-theme"
    ],
    "projectHome": "/Users/rafaelcg/Documents/htdocs/"
  },
  "minimap": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-php, v0.3.6
color-picker, v2.0.2
emmet, v2.3.10
magento-theme, v0.0.0
minimap, v4.9.1

# Dev
No dev packages
```

**Comment by abe33** [comment] 2015-06-01 13:54
@rafaelstz This is not the same issue, but 4.9.2 fix this typo ;)

**Comment by rafaelstz** [comment] 2015-06-01 14:16
:+1: Thanks! :smile:

**Comment by abe33** [comment] 2015-06-04 21:01
I guess I can close this one.

**Closed by abe33** 2015-06-04 21:01 UTC
Labels: bug
