### ISSUE TITLE
Minimap has conflicat with git-plus

### ISSUE THREAD

**Issue by q454067820** [atom-minimap/minimap#415] opened 2015-11-27 03:25 UTC
[Enter steps to reproduce below:]

When I save commit in the git-plus,the minimap throw an error.

**Atom Version**: 1.2.3
**System**: Mac OS X 10.10.4
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.16.1

### Stack Trace

Uncaught TypeError: Cannot read property 'getTextEditorScaledHeight' of null

```
At /Users/zhangjialin/.atom/packages/minimap/lib/minimap-element.coffee:393

TypeError: Cannot read property 'getTextEditorScaledHeight' of null
    at atom-text-editor-minimap.MinimapElement.update (/Users/zhangjialin/.atom/packages/minimap/lib/minimap-element.coffee:393:5)
    at /Users/zhangjialin/.atom/packages/minimap/lib/minimap-element.coffee:367:5
```

### Commands

```
  3x -2:35.6.0 core:move-down (atom-text-editor.editor.is-focused)
     -2:30.8.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -2:30.7.0 editor:newline (atom-text-editor.editor.is-focused)
 11x -2:28.4.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:17.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:11.6.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  2x -2:11 editor:delete-to-beginning-of-line (atom-text-editor.editor.is-focused)
     -0:26 git-plus:menu (atom-text-editor.editor.is-focused)
  5x -0:23.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:22.1.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:21.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  8x -0:18.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:05.6.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:05.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:05.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:04.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "disabledPackages": [
      "atom-autocomplete-php"
    ]
  },
  "minimap": {}
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.3
atom-beautify, v0.28.19
atom-material-syntax, v0.2.5
atom-material-ui, v0.8.0
autoclose-html, v0.19.0
emmet, v2.3.14
file-icons, v1.6.12
git-plus, v5.6.6
jquery-snippets, v11.0.0
language-javascript-jsx, v0.3.7
minimap, v4.16.1
php-cs-fixer, v2.5.1
pretty-json, v0.4.1
semantic-ui, v1.0.7

# Dev
No dev packages
```

**Comment by abe33** [comment] 2015-11-27 08:48
Hi @q454067820, it looks like a duplicate of #410, and as far as I can tell you encounter the same issue than in https://github.com/atom-minimap/minimap/issues/410#issuecomment-158547845 where the old version of the minimap element was still active.

**Closed** 2015-12-17 14:07 UTC
