### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getCharWidth' of null

### ISSUE THREAD

**Issue by liuzhen** [atom-minimap/minimap#379] opened 2015-08-28 03:57 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.8
**System**: Mac OS X 10.10.4
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.13.2

### Stack Trace

Uncaught TypeError: Cannot read property 'getCharWidth' of null

```
At /Users/liuzhen/.atom/packages/minimap/lib/minimap-element.coffee:430

TypeError: Cannot read property 'getCharWidth' of null
    at atom-text-editor-minimap.MinimapElement.measureHeightAndWidth (/Users/liuzhen/.atom/packages/minimap/lib/minimap-element.coffee:430:38)
    at atom-text-editor-minimap.MinimapElement.attachedCallback (/Users/liuzhen/.atom/packages/minimap/lib/minimap-element.coffee:91:6)
    at atom-pane.PaneElement.activeItemChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:150:24)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:250:22)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:314:21)
    at tabs-tab.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:210:24)
    at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
  3x -0:37.3.0 core:close (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {},
  "minimap": {
    "absoluteMode": true,
    "plugins": {
      "git-diff": true,
      "linter": true,
      "selection": true,
      "find-and-replace": true
    }
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-erlang, v1.1.1
http-status-codes, v1.0.4
language-erlang, v3.0.0
language-protobuf, v0.5.0
linter, v1.4.3
linter-erlang, v0.2.0
minimap, v4.13.2
minimap-find-and-replace, v4.3.0
minimap-git-diff, v4.1.8
minimap-linter, v1.0.0
minimap-selection, v4.3.0

# Dev
No dev packages
```
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.8
**System**: Mac OS X 10.10.4
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.13.2

### Stack Trace

Uncaught TypeError: Cannot read property 'getCharWidth' of null

```
At /Users/liuzhen/.atom/packages/minimap/lib/minimap-element.coffee:430

TypeError: Cannot read property 'getCharWidth' of null
    at atom-text-editor-minimap.MinimapElement.measureHeightAndWidth (/Users/liuzhen/.atom/packages/minimap/lib/minimap-element.coffee:430:38)
    at atom-text-editor-minimap.MinimapElement.attachedCallback (/Users/liuzhen/.atom/packages/minimap/lib/minimap-element.coffee:91:6)
    at atom-pane.PaneElement.activeItemChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:150:24)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:250:22)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:314:21)
    at tabs-tab.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:210:24)
    at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
  3x -0:37.3.0 core:close (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {},
  "minimap": {
    "absoluteMode": true,
    "plugins": {
      "git-diff": true,
      "linter": true,
      "selection": true,
      "find-and-replace": true
    }
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-erlang, v1.1.1
http-status-codes, v1.0.4
language-erlang, v3.0.0
language-protobuf, v0.5.0
linter, v1.4.3
linter-erlang, v0.2.0
minimap, v4.13.2
minimap-find-and-replace, v4.3.0
minimap-git-diff, v4.1.8
minimap-linter, v1.0.0
minimap-selection, v4.3.0

# Dev
No dev packages
```

**Comment by Bjoernsen** [comment] 2015-08-28 04:33
[Enter steps to reproduce below:]

1. I opend a .rb file

**Atom Version**: 1.0.8
**System**: Ubuntu 14.04.2
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.13.2


### Stack Trace

Uncaught TypeError: Cannot read property 'getCharWidth' of null

```
At /home/bjoern/.atom/packages/minimap/lib/minimap-element.coffee:430

TypeError: Cannot read property 'getCharWidth' of null
    at atom-text-editor-minimap.MinimapElement.measureHeightAndWidth (/home/bjoern/.atom/packages/minimap/lib/minimap-element.coffee:430:38)
    at atom-text-editor-minimap.MinimapElement.attachedCallback (/home/bjoern/.atom/packages/minimap/lib/minimap-element.coffee:91:6)
    at atom-pane.PaneElement.activeItemChanged (/usr/share/atom/resources/app.asar/src/pane-element.js:150:24)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at Pane.module.exports.Pane.setActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:250:22)
    at Pane.module.exports.Pane.activateItem (/usr/share/atom/resources/app.asar/src/pane.js:314:21)
    at tabs-tab.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:210:24)
    at space-pen-ul.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at space-pen-ul.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -3:58.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -3:57.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:56.9.0 core:delete (atom-text-editor.editor.is-focused)
     -3:56.3.0 core:paste (atom-text-editor.editor.is-focused)
 13x -3:55.5.0 core:move-up (atom-text-editor.editor.is-focused)
     -3:52.6.0 core:select-down (atom-text-editor.editor.is-focused)
     -3:51 core:cut (atom-text-editor.editor.is-focused)
 11x -3:50.6.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -3:49.3.0 core:move-up (atom-text-editor.editor.is-focused)
     -3:48.7.0 core:move-down (atom-text-editor.editor.is-focused)
     -3:48.2.0 core:paste (atom-text-editor.editor.is-focused)
     -3:47.8.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -3:47.2.0 core:delete (atom-text-editor.editor.is-focused)
  2x -3:45.8.0 core:save (atom-text-editor.editor.is-focused)
 11x -0:24.1.0 core:undo (atom-text-editor.editor.is-focused)
     -0:16 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "railscast-theme"
    ],
    "audioBeep": false,
    "autoHideMenuBar": true
  },
  "minimap": {
    "plugins": {
      "git-diff": true
    }
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-emojis, v2.2.2
color-picker, v2.0.11
file-icons, v1.6.9
git-tab-status, v1.9.2
highlight-line, v0.11.0
highlight-selected, v0.10.1
language-haml, v0.21.0
linter, v1.4.3
linter-haml, v1.0.0
linter-rubocop, v0.3.3
markdown-scroll-sync, v0.4.0
minimap, v4.13.2
minimap-git-diff, v4.1.8
project-manager, v1.16.0
railscast-theme, v0.3.0

# Dev
No dev packages
```

**Comment by baelter** [comment] 2015-08-28 07:03
Got same error while opening a json file.

**Atom Version**: 1.0.7
**System**: "Manjaro Linux"
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.13.2


### Stack Trace

Uncaught TypeError: Cannot read property 'getCharWidth' of null

```
At /home/anders/.atom/packages/minimap/lib/minimap-element.coffee:430

TypeError: Cannot read property 'getCharWidth' of null
  at atom-text-editor-minimap.MinimapElement.measureHeightAndWidth (/home/anders/.atom/packages/minimap/lib/minimap-element.coffee:430:38)
  at atom-text-editor-minimap.MinimapElement.attachedCallback (/home/anders/.atom/packages/minimap/lib/minimap-element.coffee:91:6)
  at atom-pane.PaneElement.activeItemChanged (/usr/share/atom/resources/app.asar/src/pane-element.js:150:24)
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:242:22)
  at Pane.module.exports.Pane.activateItem (/usr/share/atom/resources/app.asar/src/pane.js:306:21)
  at /usr/share/atom/resources/app.asar/src/workspace.js:489:16
  at _fulfilled (/usr/share/atom/resources/app.asar/node_modules/q/q.js:794:54)
  at self.promiseDispatch.done (/usr/share/atom/resources/app.asar/node_modules/q/q.js:823:30)
  at Promise.promise.promiseDispatch (/usr/share/atom/resources/app.asar/node_modules/q/q.js:756:13)
  at /usr/share/atom/resources/app.asar/node_modules/q/q.js:817:14
  at flush (/usr/share/atom/resources/app.asar/node_modules/q/q.js:110:17)
  at process._tickCallback (node.js:357:13)

```

### Commands

```
     -1:14.3.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -1:13.8.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:13.1.0 core:delete (atom-text-editor.editor.is-focused)
  3x -1:07.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:57.9.0 core:copy (atom-text-editor.editor.is-focused)
     -0:56.5.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:56.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:56.3.0 core:paste (atom-text-editor.editor.is-focused)
     -0:54.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:52.7.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:48 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:23.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:17.9.0 core:copy (atom-text-editor.editor.is-focused)
     -0:14.5.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:03.8.0 core:cancel (atom-notification.error.icon.icon-flame.native-key-bindings.has-detail.has-close)
     -0:01.6.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "projectHome": "/home/anders/Projects",
    "autoHideMenuBar": true,
    "ignoredNames": [
      ".git"
    ],
    "disabledPackages": [
      "json-schema",
      "markdown-preview-opener"
    ]
  },
  "minimap": {
    "plugins": {
      "highlight-selected": true,
      "git-diff": true,
      "selection": true,
      "color-highlight": true,
      "bookmarks": true,
      "find-and-replace": true
    }
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
atom-beautify, v0.28.11
atom-ternjs, v0.7.2
autoclose-html, v0.18.0
autocomplete-ctags, v0.3.1
autocomplete-modules, v1.1.0
autocomplete-paths, v1.0.2
autocomplete-python, v0.5.3
autocomplete-sass, v0.1.0
color-picker, v2.0.11
compare-files, v0.6.2
css-snippets, v0.8.0
custom-title, v1.0.1
disable-keybindings, v0.5.0
docblockr, v0.7.3
editorconfig, v1.1.1
external-open, v0.6.1
file-icons, v1.6.9
filesize, v0.2.0
flex-tool-bar, v0.5.0
git-log, v0.4.1
go-plus, v3.5.1
highlight-selected, v0.10.1
language-diff, v0.3.1
language-groovy, v0.4.0
language-nginx, v0.5.4
language-qml, v1.0.0
language-rspec, v0.3.0
language-svg, v0.8.0
linter, v1.4.3
linter-clang, v3.1.3
linter-coffeelint, v1.0.2
linter-csslint, v1.0.5
linter-htmlhint, v0.1.1
linter-javac, v1.1.0
linter-jscs, v2.0.4
linter-jshint, v1.1.5
linter-jsonlint, v0.1.4
linter-less, v2.1.0
linter-php, v1.0.3
linter-pylint, v1.0.0
linter-ruby, v1.0.2
linter-scss-lint, v2.0.0
linter-shellcheck, v1.0.1
linter-xmllint, v0.0.7
local-history, v3.2.3
markdown-scroll-sync, v0.4.0
minimap, v4.13.2
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.3.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.0
minimap-selection, v4.3.0
pigments, v0.11.0
pretty-json, v0.4.1
project-manager, v1.16.0
regex-railroad-diagram, v0.8.4
rspec-snippets, v0.4.0
simple-drag-drop-text, v0.2.3
svg-preview, v0.6.1
symbol-gen, v1.0.0
symbols-tree-view, v0.9.3
sync-settings, v0.6.0
synced-sidebar, v0.4.0
tabs-to-spaces, v0.11.1
tool-bar, v0.1.8
trailing-spaces, v0.3.2
zentabs, v0.8.6

# Dev
autocomplete-plus, v2.19.0
symbol-gen, v1.0.0
```

**Comment by abe33** [comment] 2015-08-28 07:55
Hi there, I believe the issue is the same issue than #374, please see my reply [here](https://github.com/atom-minimap/minimap/issues/374#issuecomment-135363998). 

I'll close this issue as soon as you confirm that a reload fix things for you.

**Comment by Bjoernsen** [comment] 2015-08-28 08:47
I reloaded Atom. Up to now, I was not able to reproduce the error.

**Comment by baelter** [comment] 2015-08-28 08:53
Seems to be do the trick

**Comment by abe33** [comment] 2015-08-28 09:48
Ok glad to hear that, and again, sorry for the inconvenience. I'll close the issue then.

**Closed by abe33** 2015-08-28 09:48 UTC
