### ISSUE TITLE
Autohide plugin not working anymore - what's the overall status of autohide?

### ISSUE THREAD

**Issue by ThomasLandauer** [atom-minimap/minimap#780] opened 2021-01-31 22:32 UTC
Autohiding is not working anymore - I think since about 2 weeks, but there were so many releases that I can't say when exactly.

I have [ansballard/minimap-autohider](https://github.com/ansballard/minimap-autohider) installed. But under Settings > Plugins (of Minimap) I have **two** entries:
* Plugins Minimap-autohide
* Plugins Minimap-autohider

Where is the second coming from? And no matter if I deactivate `ansballard/minimap-autohider`, those two entries remain. And also (if I remember correctly) there used to be an autohide entry when clicking on the options icon inside the minimap itself, and this is now gone.

So in total: Autohiding is not working anymore for me :-(

**Comment by aminya** [comment] 2021-01-31 23:07
@ThomasLandauer Thanks for the report. I will investigate this.

**Comment by UziTech** [comment] 2021-02-01 18:50
> Where is the second coming from?

When you install a minimap plugin, minimap creates a config for that plugin to show in the settings. When you uninstall a plugin minimap does not remove that config so you reinstall that plugin and keep the same settings for the plugin that you had. You can manually delete the plugin settings in `~\.atom\config.cson` `"*"->minimap->plugins`

**Comment by ThomasLandauer** [comment] 2021-02-01 21:13
Thanks, after manually deleting the lines from this file, then uninstalling and reinstalling `ansballard/minimap-autohider`, I now have just *one* entry in the settings.

However, the main issue remains: Autohide is not working anymore - here's the corresponding issue at the plugin: https://github.com/ansballard/minimap-autohider/issues/19

**Comment by ansballard** [comment] 2021-02-01 21:51
Apologies, autohider maintainer here, I've been pretty swamped the past few weeks so I haven't been able to tackle this issue. I can say that the autohide -> autohider is because I forked autohide and published a separate version under autohider, so that's why they're different plugins entirely. I did publish a fix somewhat recently that had to do with waiting for an atom hook that minimal proper started using, not sure if that's relevant but I'll link the PR here after work tonight.

**Comment by UziTech** [comment] 2021-02-01 22:35
It looks like the issue is that `minimap.minimapElement` and `atom.views.getView(minimap)` are different elements.

minimap-autohider does everything on `atom.views.getView(minimap)` and minimap displays `minimap.minimapElement`

I think this is something that should be fixed in minimap.

**Closed** 2021-02-01 23:41 UTC
Labels: plugin
