### ISSUE TITLE
Cannot open new file when minimap extension is installed

### ISSUE THREAD

**Issue by smrfeld** [atom-minimap/minimap#696] opened 2020-03-12 04:09 UTC
When the minimap extension is installed and enabled:
- Opening atom (with no previous open windows), it opens a new window, but no new file.
- Pressing new file (command-n) has no effect.

Minimap: 4.29.9
Atom: 1.45.0

**Comment by smrfeld** [comment] 2020-03-12 04:37
I quickly discovered that it was when both minimap and the "docblock-python" package were installed.

Enabling only ONE of the two works (either one). Enabling both gives the errors above.

**Comment by UziTech** [comment] 2020-11-21 06:35
duplicate of #693

**Closed by UziTech** 2020-11-21 06:35 UTC
