### ISSUE TITLE
Dragging mouse outside range stops scrolling

### ISSUE THREAD

**Issue by multiwebinc** [atom-minimap/minimap#647] opened 2018-01-25 01:59 UTC
Platform: Ubuntu 17.10 64 bit

Dragging the highlighted area on the minimap vertically up will stop the drag as soon as your mouse reaches the tabs, so when you move your mouse back down (still dragging) it doesn't scroll the minimap anymore. Similarly dragging vertically down or horizontally, as soon as your mouse leaves the Atom window the scrolling stops.

**Comment by UziTech** [comment] 2020-11-21 07:47
duplicate of #314

**Closed by UziTech** 2020-11-21 07:47 UTC
