### ISSUE TITLE
Unexepected Error, Still works

### ISSUE THREAD

**Issue by AwkwardNoah** [atom-minimap/minimap#518] opened 2016-10-08 06:58 UTC
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Microsoft Windows 10 Home
**Thrown From**: 'minimap-hide' package, vundefined
### Stack Trace

Uncaught TypeError: Cannot read property 'minimapForEditor' of null

```
At /C:/Users/Noah%20Meeks/.atom/packages/minimap-hide/lib/minimap-hide.coffee:55

TypeError: Cannot read property 'minimapForEditor' of null
    at Object.module.exports.show (file:///C:/Users/Noah Meeks/.atom/packages/minimap-hide/lib/minimap-hide.coffee:40:49)
    at file:///C:/Users/Noah Meeks/.atom/packages/minimap-hide/lib/minimap-hide.coffee:29:8
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Noah Meeks\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Noah Meeks\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at C:\Users\Noah Meeks\AppData\Local\atom\app-1.10.2\resources\app.asar\src\pane-container.js:346:27
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Noah Meeks\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Noah Meeks\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (C:\Users\Noah Meeks\AppData\Local\atom\app-1.10.2\resources\app.asar\src\pane.js:284:22)
    at Pane.module.exports.Pane.activateItem (C:\Users\Noah Meeks\AppData\Local\atom\app-1.10.2\resources\app.asar\src\pane.js:433:21)
    at atom-tabs.TabBarView.onMouseDown (C:\Users\Noah Meeks\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:662:19)
```
### Commands

```
     -4:40.9.0 core:undo (atom-text-editor.editor.is-focused)
     -4:35.1.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -4:35 core:cancel (atom-text-editor.editor.mini.is-focused)
     -4:32.1.0 linter:next-error (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-one-dark-ui)
  2x -4:20 core:backspace (atom-text-editor.editor.is-focused)
     -4:18 core:move-down (atom-text-editor.editor.is-focused)
     -4:17.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:05.9.0 script:run (atom-text-editor.editor.is-focused)
     -3:48.5.0 script:kill-process (div.am-panel.tool-panel.panel-bottom.native-key-bindings.script-view)
  4x -3:41.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:40 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -3:38.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -3:37.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:01.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:00.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:29.2.0 core:backspace (div.package-detail.panels-item)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "qolor"
    ],
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
animated-page-scroll, v1.0.0 (active)
atom-typescript, v10.1.7 (active)
eval-javascript, v1.2.0 (inactive)
git-time-machine, v1.5.3 (inactive)
highlight-selected, v0.11.2 (active)
linter, v1.11.18 (active)
linter-js-standard, v3.4.1 (active)
minimap, v4.25.0 (active)
minimap-bookmarks, v0.4.2 (active)
minimap-cursorline, v0.2.0 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-git-diff, v4.3.1 (active)
minimap-highlight-selected, v4.4.0 (active)
minimap-selection, v4.4.0 (active)
qolor, v0.4.0 (inactive)
remote-atom, v1.3.9 (active)
Remote-FTP, v0.9.0 (active)
spotify-remote, v1.0.2 (active)
tree-view-git-branch, v0.1.2 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (active)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (active)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by abe33** [comment] 2016-10-13 12:49
Hi @AwkwardNoah, it looks the issue was already reported in T-800/atom-minimap-hide/issues/3. I think you should probably subscribe to that issue as it's an error related to a plugin behaviour.

**Comment by aminya** [comment] 2020-11-21 06:24
Duplicate of https://github.com/rndAdn/atom-minimap-hide/issues/3

**Closed by aminya** 2020-11-21 06:24 UTC
