### ISSUE TITLE
Uncaught TypeError: this.textEditor.displayBuffer.getMaxScrollTop is not a function

### ISSUE THREAD

**Issue by Alchiadus** [atom-minimap/minimap#387] opened 2015-09-27 08:57 UTC
[Enter steps to reproduce below:]

1. Build and start the latest `Atom/master`. At least [`f17767a`](https://github.com/atom/atom/commit/f17767a2bcea81eb51faae646757fb1dd907cabf) or newer.
2. Open a file with minimap enabled.

`DisplayBuffer::getMaxScrollTop` is removed in this PR: https://github.com/atom/atom/pull/8905

---

**Atom Version**: 1.2.0-dev-e9a8646
**System**: Microsoft Windows 10 Pro Insider Preview, Build 10547
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.13.4

### Stack Trace

Uncaught TypeError: this.textEditor.displayBuffer.getMaxScrollTop is not a function

```
At /C:/Users/Philippe/.atom/packages/minimap/lib/minimap.coffee:169

TypeError: this.textEditor.displayBuffer.getMaxScrollTop is not a function
    at Minimap.module.exports.Minimap.getTextEditorMaxScrollTop (C:\Users\Philippe\.atom\packages\minimap\lib\minimap.coffee:200:46)
    at Minimap.module.exports.Minimap.getTextEditorScrollRatio (C:\Users\Philippe\.atom\packages\minimap\lib\minimap.coffee:216:36)
    at Minimap.module.exports.Minimap.getCapedTextEditorScrollRatio (C:\Users\Philippe\.atom\packages\minimap\lib\minimap.coffee:223:50)
    at Minimap.module.exports.Minimap.getScrollTop (C:\Users\Philippe\.atom\packages\minimap\lib\minimap.coffee:334:17)
    at Minimap.module.exports.Minimap.getLastVisibleScreenRow (C:\Users\Philippe\.atom\packages\minimap\lib\minimap.coffee:322:17)
    at Minimap.module.exports.DecorationManagement.emitRangeChanges (C:\Users\Philippe\.atom\packages\minimap\lib\mixins\decoration-management.coffee:261:31)
    at Minimap.module.exports.DecorationManagement.emitDecorationChanges (C:\Users\Philippe\.atom\packages\minimap\lib\mixins\decoration-management.coffee:253:6)
    at Minimap.module.exports.DecorationManagement.decorateMarker (C:\Users\Philippe\.atom\packages\minimap\lib\mixins\decoration-management.coffee:224:6)
    at MinimapGitDiffBinding.module.exports.MinimapGitDiffBinding.markRange (C:\Users\Philippe\.atom\packages\minimap-git-diff\lib\minimap-git-diff-binding.coffee:63:14)
    at MinimapGitDiffBinding.module.exports.MinimapGitDiffBinding.addDecorations (C:\Users\Philippe\.atom\packages\minimap-git-diff\lib\minimap-git-diff-binding.coffee:49:10)
    at MinimapGitDiffBinding.module.exports.MinimapGitDiffBinding.updateDiffs (C:\Users\Philippe\.atom\packages\minimap-git-diff\lib\minimap-git-diff-binding.coffee:42:8)
    at Immediate._onImmediate (C:\Users\Philippe\.atom\packages\minimap-git-diff\lib\minimap-git-diff-binding.coffee:1:1)
    at processImmediate [as _immediateCallback] (timers.js:371:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-syntax"
    ],
    "disabledPackages": [
      "autoflow",
      "autosave",
      "background-tips",
      "bookmarks",
      "exception-reporting",
      "go-to-line",
      "incompatible-packages",
      "markdown-preview",
      "metrics",
      "package-generator",
      "symbols-view",
      "update-package-dependencies",
      "welcome"
    ],
    "ignoredNames": [
      "desktop.ini"
    ]
  },
  "minimap": {
    "displayPluginsControls": false,
    "plugins": {
      "codeglance": true,
      "find-and-replace": true,
      "git-diff": true,
      "pigments": true,
      "selection": true,
      "highlight-selected": true
    },
    "scrollAnimation": true
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.7.2
autoclose-html, v0.19.0
autocomplete-emojis, v2.2.2
autocomplete-paths, v1.0.2
base16-syntax, v1.5.0
color-picker, v2.0.12
column-select, v0.2.0
editorconfig, v1.2.0
file-icons, v1.6.9
highlight-selected, v0.10.1
language-latex, v0.6.1
language-lua, v0.9.4
language-powershell, v2.1.0
linter, v1.6.0
linter-coffeelint, v1.1.0
linter-csslint, v1.0.5
linter-eslint, v3.0.2
linter-less, v2.1.0
linter-lua, v1.0.0
markdown-preview-plus, v2.1.1
minimap, v4.13.4
minimap-find-and-replace, v4.3.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-selection, v4.3.0
pdf-view, v0.27.0
sublime-style-column-selection, v1.3.0
tab-control, v0.6.8

# Dev
base16-syntax, v1.5.0
latex-essentials, v0.0.0
```

**Comment by as-cii** [comment] 2015-09-28 06:40
Thanks for keeping an eye on this, @Alchiadus.

@abe33: the method in question was not part of the public API (and wasn't either present in `TextEditor`), therefore I went ahead and deprecated it. In the new version you should be able to replicate its behavior by using `TextEditorElement::getScrollHeight()`.

I am not sure this ought to be included in the public API, but maybe it should. What do you think?

**Comment by abe33** [comment] 2015-09-28 08:37
That was a bold move... 
I still got errors even after the change: 

```
Uncaught TypeError: Cannot read property 'getScrollTop' of nullTextEditorElement.getScrollTop @ text-editor-element.coffee:248module.exports.TextEditor.getScrollTop @ text-editor.coffee:3012module.exports.Minimap.getTextEditorScrollRatio @ minimap.coffee:218module.exports.Minimap.getCapedTextEditorScrollRatio @ minimap.coffee:225module.exports.Minimap.getScrollTop @ minimap.coffee:336module.exports.Minimap.getLastVisibleScreenRow @ minimap.coffee:324module.exports.DecorationManagement.emitRangeChanges @ /Users/cedric/github/minimap/lib/mixins/decoration-management.coffee:232module.exports.DecorationManagement.emitDecorationChanges @ /Users/cedric/github/minimap/lib/mixins/decoration-management.coffee:225module.exports.DecorationManagement.decorateMarker @ /Users/cedric/github/minimap/lib/mixins/decoration-management.coffee:191module.exports.MinimapGitDiffBinding.markRange @ /Users/cedric/github/minimap-git-diff/lib/minimap-git-diff-binding.coffee:103module.exports.MinimapGitDiffBinding.addDecorations @ /Users/cedric/github/minimap-git-diff/lib/minimap-git-diff-binding.coffee:76module.exports.MinimapGitDiffBinding.updateDiffs @ /Users/cedric/github/minimap-git-diff/lib/minimap-git-diff-binding.coffee:60__bind @ /Users/cedric/github/minimap-git-diff/lib/minimap-git-diff-binding.coffee:3processImmediate @ timers.js:371```

Raised when moving a file by drag and drop to another pane.

Another one is raised from the wrap guide package: 

```
Uncaught TypeError: Cannot read property 'onDidChangeScrollLeft' of nullTextEditorElement.onDidChangeScrollLeft @ text-editor-element.coffee:225module.exports.TextEditor.onDidChangeScrollLeft @ text-editor.coffee:437WrapGuideElement.handleEvents @ wrap-guide-element.coffee:28WrapGuideElement.initialize @ wrap-guide-element.coffee:7(anonymous function) @ main.coffee:11(anonymous function) @ workspace.coffee:198(anonymous function) @ workspace.coffee:349module.exports.Emitter.emit @ /Users/cedric/github/atom/node_modules/event-kit/lib/emitter.js:82module.exports.PaneContainer.addedPaneItem @ pane-container.coffee:221(anonymous function) @ pane-container.coffee:214module.exports.Emitter.emit @ /Users/cedric/github/atom/node_modules/event-kit/lib/emitter.js:82module.exports.Pane.addItem @ pane.coffee:363module.exports.Pane.moveItemToPane @ pane.coffee:418module.exports.TabBarView.moveItemBetweenPanes @ tab-bar-view.coffee:395module.exports.TabBarView.onDrop @ tab-bar-view.coffee:342__bind @ tab-bar-view.coffee:1jQuery.event.dispatch @ /Users/cedric/github/atom/node_modules/jquery/dist/jquery.js:4435jQuery.event.add.elemData.handle @ /Users/cedric/github/atom/node_modules/jquery/dist/jquery.js:4121```

I'll make sure the patch won't be available for the current Atom version, cause it'll probably breaks with versions before the deprecations

**Comment by as-cii** [comment] 2015-09-28 08:43
>  In the new version you should be able to replicate its behavior by using TextEditorElement::getScrollHeight().

I should probably have emphasized this more but, if you want to keep compatibility for both versions, you can use methods on `TextEditor` (at least, for a couple of Atom versions), as we have shimmed them to call `TextEditorElement`. Sorry about that.

Please, note that they will be deprecated at some point, so you should probably switch to `TextEditorElement` methods anyways as soon as possible (maybe after a new Atom release lands).

Thanks, @abe33.

**Comment by abe33** [comment] 2015-09-28 11:03
I'm trying to figure how to get rid of all the deprecations, but it has a major impact on the minimap behavior. Properties that were available even when the text editor was not in the DOM are no longer available, etc... I don't know how long it will take to fix all the broken specs...

**Comment by abe33** [comment] 2015-10-07 09:02
A quick update, the `cn-fix-deprecations` branch is now fully functional with Atom's master, I'm just waiting for the release of 1.0.20 to merge and publish it.

**Comment by steelbrain** [comment] 2015-10-14 10:57
@abe33 You can just bump the target atom version instead of waiting for a release.

**Comment by abe33** [comment] 2015-10-14 13:20
@steelbrain sadly not. 
I should bump it to 1.0.20, but it would still fail for people using the 1.1.0-beta1, as it doesn't have these changes. 
I'll have to make the same changes than in Pigments, meaning supporting both API and then release a patch, and finally removing this support when 1.0.20 gets out.

**Comment by abe33** [comment] 2015-10-22 14:58
Ok, so I reverted many changes and published a new version with an adapter layer to handle the differences, let me know if it fixes things for you.

**Comment by abe33** [comment] 2015-10-23 11:53
Looks like most people with this issue confirmed the latest version fix these errors, I'm closing this issue then.

**Closed by abe33** 2015-10-23 11:53 UTC

**Comment by jchannon** [comment] 2015-10-29 22:54
1.1.0 is now out and this error now appears :smile:

**Comment by M4GNV5** [comment] 2015-10-29 23:07
yep -,-

**Comment by yupswing** [comment] 2015-10-30 08:33
reopen please.
in atom 1.1.0 this error is back.

**Comment by abe33** [comment] 2015-10-30 08:38
@jchannon, @M4GNV5, @yupswing Are you sure you have the latest version installed?

As far as I can tell, @M4GNV5 is using v4.12.1, the version that handles both pre-1.1 and 1.1 is v4.15.0.

**Comment by Alchiadus** [comment] 2015-10-30 08:49
I just opened Atom `v1.1.0` and I can confirm that I have no errors (using `v4.15.0`).

I typically use the latest master of Atom, so that is how I got the minimap update, but the engines field hasn't changed so everyone should be receiving the update?

**Comment by abe33** [comment] 2015-10-30 10:05
v4.15 engine field is no longer restricted to > 1.0.19 so yes they should get the update (but they should also have been notified of v4.14 as well as its engine field should match 1.1)

**Comment by jchannon** [comment] 2015-10-30 10:16
Just checked and I had an old version of the plugin, sorry

**Comment by M4GNV5** [comment] 2015-10-30 11:27
same for me, updating to `4.15.0`fixed it

**Comment by peterfraedrich** [comment] 2015-10-30 20:24
Please reopen:
Seeing this issue on Minimap v4.15.1 with Atom 1.1.0

**Comment by abe33** [comment] 2015-10-31 12:00
@peterfraedrich Yeah, it's a recurring problem with custom elements, as you can't unregister them, if a change is made in an update, the updated version won't be able to register (as one is already registered), leading to this kind of nasty behaviour. I think the Minimap will have to move on a new version without custom elements to definitely get rid of these issues.

**Comment by bencasalino** [comment] 2015-11-01 16:18
kinda new to minimap and atom, is it possible to get an older working version instead of waiting for the new one? thanks!

**Comment by abe33** [comment] 2015-11-01 16:22
@bencasalino Not sure to understand what you mean? What is your problem?

**Comment by bencasalino** [comment] 2015-11-01 16:39
nvm i figured it out thanks tho, ty!!!
